---
- name: Install nginx on Debian
  become: yes
  apt:
    name: nginx
    state: latest

- name: Create nginx user
  user:
    name: nginx
    system: True
    create_home: False
    shell: /sbin/nologin

- name: Copy nginx configs
  become: yes
  copy:
    src: "{{ local_nginx_conf_path }}"
    dest: "{{ etc_path }}"
    owner: root
    group: "{{root_group}}"
    mode: 0644

- name: Inserting variables in nginx
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ templates_destination }}/{{ item.path | regex_replace('\\.j2$', '') }}"
  with_community.general.filetree: "{{ templates_source }}"
  when: item.state == 'file'
  notify:
    - validate nginx configuration
    - restart nginx
