---
- name: Copy docker-compose file
  template:
    src:  "{{ docker_compose_template_src }}"
    dest: "{{ docker_compose_file_server_dest }}"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ docker_compose_file_server_dest }}"
    