---
- name: Check current docker-compose version.
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Delete existing docker-compose version if it's different.
  become: yes
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Install Docker Compose (if configured).
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    dest: "{{ docker_compose_path }}"
    mode: 0755

- name: Install Docker.
  become: yes
  package: 
    name: libffi-dev
    state: present

- name: Install python3-pip
  package:
    name: python3-pip
    state: present

- name: Install python docker
  apt: name=python3-docker state=latest

- name: Install python docker-compose
  apt: name=python3-compose state=latest

#- name: add docker-py python pip library
#  become: true
#  pip:
#    name: docker-py

#- name: add docker python pip library
#  become: true
#  pip:
#    name: docker