---
- name: Ensure old versions of Docker are not installed.
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine
  tags: docker_install_apt

- name: Ensure dependencies are installed.
  become: yes
  apt:
    name: ["apt-transport-https", "ca-certificates", "gnupg"]
    state: present
  tags: docker_install_apt

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags: docker_install_apt

- name: Add docker repository to apt
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_lsb.codename }}  stable"
    state: present
  tags: docker_install_apt

- name: Install Docker.
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
    - "docker-ce-rootless-extras"
  tags: docker_install_apt

- name: Check docker is active
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker_install_apt

- name: Add users to the docker group
  become: yes
  user:
    name:   "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ansible_user}}"
  tags: docker_install_apt

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker_install_apt