---
- name: Ensure old versions of Docker are not installed.
  become: yes
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-engine

- name: Ensure dependencies are installed.
  become: yes
  apt:
    name: ["apt-transport-https", "ca-certificates", "gnupg"]
    state: present

- name: Add GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add docker repository to apt
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ ansible_lsb.codename }}  stable"
    state: present

- name: Install Docker.
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "docker-ce"
    - "docker-ce-cli"
    - "containerd.io"
    - "docker-ce-rootless-extras"

- name: Check docker is active
  service:
    name: docker
    state: started
    enabled: yes

- name: Add users to the docker group
  become: yes
  user:
    name:   "{{ item }}"
    groups: docker
    append: yes
  with_items:
    - "{{ansible_user}}"

- name: Ensure Docker is started and enabled at boot.
  become: yes
  service:
    name: docker
    state: started
    enabled: yes


- include_tasks: docker-compose-install.yml
  when: docker_install_compose

- include_tasks: docker-image-pull.yml
  tags: pull_images

- include_tasks: docker-compose-start.yml
  tags: start_docker_compose