---
- include_tasks: docker-install-apt.yml
  tags: docker_install_apt

- include_tasks: docker-binary-depends-pull.yml
  tags: docker_binary_depends_pull

- include_tasks: docker-install-binary.yml
  tags: docker_install_binary

- include_tasks: docker-compose-install-apt.yml
  tags: docker_compose_install_apt

- include_tasks: docker-compose-install-binary.yml
  tags: docker_compose_install_binary

- include_tasks: docker-image-pull.yml
  tags: pull_images

- include_tasks: docker-compose-start.yml
  tags: start_docker_compose