global:
 scrape_interval: 1m
scrape_configs:
 - job_name: “prometheus”
   scrape_interval: 1m
   static_configs:
   - targets:
     - "{{ ip_prometheus }}" # 192.168.15.100:9090
  #  - targets: [“10.236.128.200:9090”]
 - job_name: cadvisor
   scrape_interval: 5s
   static_configs:
   - targets:
     - "{{ ip_cadvisor }}" # 192.168.15.100:8080
 - job_name: docker-exporter
   scrape_interval: 5s
   static_configs:
   - targets:
     - "{{ ip_docker_exporter }}" # 192.168.15.100:9417

 - job_name: “node”
   scrape_interval: 30s
   static_configs:
  #  - targets: ["10.236.128.200:9100"]
   - targets:
     - "{{ ip_node }}" # 192.168.15.100:9100

 - job_name: local-manager
   scrape_interval: 15s
   metrics_path: /metric/state_camera
   static_configs:
   - targets:
     - "{{ ip_local_manager }}" # 192.168.15.100:31002
